services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - composer-cache:/tmp/composer-cache
      - vendor:/app/vendor
    environment:
      COMPOSER_CACHE_DIR: /tmp/composer-cache

volumes:
  composer-cache:
  vendor:
